name: 提交反馈
description: 提交任何反馈或建议
title: "（一句话总结你的内容）"
body:
  - type: markdown
    attributes:
      value: |
        请先在issue中搜索（含已关闭的issue），确认所提出的内容未被提出过。
        ⚠️ 警告：未按本模板填写或缺少关键信息的 Issue 将被直接关闭。 
        ⚠️ 警告：以下内容被人反复询问，特此注明此类内容不会考虑，不要在issue中提交。否则你会被视为发送垃圾信息而在本组织中被封禁：
              兼容Android 5及以下
              扫码登录
              点赞功能
              开放源代码
              推送内容重复
              不弹出更新提示框
  - type: textarea
    attributes:
      label: 内容
      description: 完整、清晰的描述你的需求，如果涉及视频播放，务必附上logcat日志（在扫码填写Cookie的网页中可导出），请勿使用大模型（如豆包）生成大段无意义内容。开发者将忽略并关闭无法进一步处理的issue。
      placeholder: 内容描述
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 我已确认所填写的内容符合以下要求，并接受或承担因胡乱填报而被关闭或封禁的结果。
      options:
        - label: 涉及视频播放相关的问题已附上Logcat日志
          required: true
        - label: 所报告的内容不属于警告中被视为垃圾信息的任何一项
          required: true
        - label: 所报告的内容由真人撰写（可能经过AI少量润色以使得表达清晰），没有直接使用AI起草issue。
          required: true
